import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
    title: "GymGo",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="bg-gray-200">
            <body className={` w-full max-w-[1920px] mx-auto bg-white`}>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
